insert into author (first_name, last_name) values ('First_Name_1', 'Last_Name_1');
insert into author (first_name, last_name) values ('First_Name_2', 'Last_Name_2');
insert into author (first_name, last_name) values ('First_Name_3', 'Last_Name_3');
insert into author (first_name, last_name) values ('First_Name_4', 'Last_Name_4');
insert into author (first_name, last_name) values ('First_Name_5', 'Last_Name_5');
insert into author (first_name, last_name) values ('First_Name_6', 'Last_Name_6');
insert into author (first_name, last_name) values ('First_Name_7', 'Last_Name_7');
insert into author (first_name, last_name) values ('First_Name_8', 'Last_Name_8');
insert into author (first_name, last_name) values ('First_Name_9', 'Last_Name_9');
insert into author (first_name, last_name) values ( 'First_Name_10', 'Last_Name_10');
insert into author (first_name, last_name) values ( 'First_Name_11', 'Last_Name_11');
insert into author (first_name, last_name) values ( 'First_Name_12', 'Last_Name_12');
insert into author (first_name, last_name) values ( 'First_Name_13', 'Last_Name_13');
insert into author (first_name, last_name) values ( 'First_Name_14', 'Last_Name_14');
insert into author (first_name, last_name) values ( 'First_Name_15', 'Last_Name_15');

insert into post (body, date, title, author_id) values ('body_1', '2020-01-09', 'title1', 1);
insert into post (body, date, title, author_id) values ('body_2', '2020-01-09', 'title2', 1);
insert into post (body, date, title, author_id) values ('body_3', '2020-01-09', 'title3', 1);
insert into post (body, date, title, author_id) values ('body_4', '2020-01-09', 'title4', 1);
insert into post (body, date, title, author_id) values ('body_5', '2020-01-09', 'title5', 1);
